/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-23 17:31:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.yh.pojo.*;
import in.yh.dao.*;
import java.util.*;

public final class showpatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/hp/OneDrive/Desktop/Health%20Management/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/YouHeal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1680249176627L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("in.yh.dao");
    _jspx_imports_packages.add("in.yh.pojo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html,\r\n");
      out.write("body,\r\n");
      out.write(".intro {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gradient-custom-2 {\r\n");
      out.write("  /* fallback for old browsers */\r\n");
      out.write("  background: #6a11cb;\r\n");
      out.write("\r\n");
      out.write("  /* Chrome 10-25, Safari 5.1-6 */\r\n");
      out.write("  background: -webkit-linear-gradient(to top, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));\r\n");
      out.write("\r\n");
      out.write("  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\r\n");
      out.write("  background: linear-gradient(to top, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td,\r\n");
      out.write("table th {\r\n");
      out.write("  text-overflow: ellipsis;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  opacity:.65;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("background-image:url(\"\");\r\n");
      out.write("background-repeat:no-repeat;\r\n");
      out.write("background-attachment:fixed;\r\n");
      out.write("background-size:100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("tbody td {\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  color: rgba(255,255,255,250);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
 
List<Appointment> alist=(List<Appointment>)session.getAttribute("alist");
DoctorDao dao=new DoctorDao();

System.out.print(alist);

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section class=\"intro\">\r\n");
      out.write("  <div class=\" h-75\" >\r\n");
      out.write("    <div class=\"mask d-flex align-items-center h-75\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("          <p class=\"text-dark  text-center h1  m-5\">Patient List</p>\r\n");
      out.write("              <table class=\"table table-dark table-lg table-hover text-white table-bordered mb-5 table-lg\">\r\n");
      out.write("               <tr class=\"table-warning\"> \r\n");
      out.write("				<th scope=\"col\">Full Name</th>\r\n");
      out.write("				<th scope=\"col\">Gender</th>\r\n");
      out.write("				<th scope=\"col\">Age</th>\r\n");
      out.write("				<th scope=\"col\">Appointment</th>\r\n");
      out.write("				<th scope=\"col\">Email</th>\r\n");
      out.write("				<th scope=\"col\">Mob No</th>\r\n");
      out.write("				<th scope=\"col\">Diseases</th>\r\n");
      out.write("				<th scope=\"col\">Doctor Name</th>\r\n");
      out.write("				<th scope=\"col\">Address</th>\r\n");
      out.write("				<th scope=\"col\">Status</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			");
 for (Appointment a : alist) {
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				\r\n");
      out.write("				");
System.out.println(dao.searchDoctorById(1).getName()); 
      out.write("\r\n");
      out.write("				<td>");
      out.print( a.getName() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(a.getGender() );
      out.write(" </td>\r\n");
      out.write("				<td>");
      out.print( a.getAge());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( a.getAppointmentdate());
      out.write(" </td>\r\n");
      out.write("				<td>");
      out.print( a.getEmail());
      out.write(" </td>\r\n");
      out.write("				<td>");
      out.print( a.getContact());
      out.write(" </td>\r\n");
      out.write("				<td>");
      out.print( a.getDisease());
      out.write(" </td>\r\n");
      out.write("				<td>");
      out.print( dao.searchDoctorById(a.getDoctorid()).getName());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( a.getAddress());
      out.write(" </td>\r\n");
      out.write("				<td>");
      out.print( a.getStatus());
      out.write(" </td>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("              </table>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
